export const supportedLanguages = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা' },
];

export const translations = {
  en: {
    nav: {
      home: 'Home',
      about: 'About the Assessment',
      assessment: 'Assessment',
      language: 'Language',
      login: 'Login',
      signUp: 'Sign up',
      admin: 'Admin',
    },
    auth: {
      welcome: 'Welcome back!',
      subtitle: 'Login to continue your career assessment journey',
      label: 'Mobile number or Email',
      password: 'Password',
      remember: 'Remember me',
      forgot: 'Forgot password?',
      login: 'Login',
      noAccount: "Don't have an account?",
      signUp: 'Sign up',
      show: 'Show',
      hide: 'Hide',
      submit: 'Login',
    },
    admin: {
      welcome: 'Welcome back, Admin!',
      subtitle: 'Login to the portal',
      label: 'Mobile number or Email',
      password: 'Password',
      remember: 'Remember me',
      forgot: 'Forgot password?',
      login: 'Login',
      noAccount: "Don't have an account?",
      signUp: 'Sign up',
      show: 'Show',
      hide: 'Hide',
    },
    register: {
      title: 'Registration',
      subtitle: 'Please fill in your details',
      fullName: 'Full Name',
      gender: 'Gender',
      email: 'Email',
      password: 'Password',
      phone: 'Phone Number',
      dob: 'Date of Birth',
      age: 'Age',
      education: 'Education Level',
      preferredField: 'Preferred Field',
      careerGoal: 'Career Goal',
      city: 'City',
      state: 'State',
      pincode: 'Pincode',
      reset: 'Reset',
      submit: 'Register',
      submitting: 'Submitting...',
      selectGender: 'Select gender',
      selectEducation: 'Select Education',
      genderMale: 'Male',
      genderFemale: 'Female',
      genderOther: 'Other',
      required: '*',
      autoCalculated: 'Auto calculated',
      placeholderName: 'Enter your full name',
      placeholderEmail: 'example@gmail.com',
      placeholderPassword: 'Enter a strong password',
      placeholderPhone: '10 digit phone number',
      placeholderField: 'e.g. IT, Marketing, Design',
      placeholderCareer: 'What do you want to become? (e.g. Software Engineer)',
      placeholderCity: 'Enter your city',
      placeholderState: 'Enter your state',
      placeholderPincode: '6 digit pincode',
      languageTitle: 'Choose your language',
      close: 'Close',
      english: 'English',
      hindi: 'हिन्दी',
      bengali: 'বাংলा',
    },
    modal: {
      title: 'Choose your language',
      close: 'Close',
    },
  },
  hi: {
    nav: {
      home: 'होम',
      about: 'मूल्यांकन के बारे में',
      assessment: 'मूल्यांकन',
      language: 'भाषा',
      login: 'लॉगिन',
      signUp: 'साइन अप',
      admin: 'एडमिन',
    },
    auth: {
      welcome: 'वापसी पर स्वागत है!',
      subtitle: 'अपने करियर मूल्यांकन को जारी रखने के लिए लॉगिन करें',
      label: 'मोबाइल नंबर या ईमेल',
      password: 'पासवर्ड',
      remember: 'याद रखें',
      forgot: 'पासवर्ड भूल गए?',
      login: 'लॉगिन',
      noAccount: 'खाता नहीं है?',
      signUp: 'साइन अप',
      show: 'दिखाएँ',
      hide: 'छुपाएँ',
      submit: 'लॉगिन',
    },
    admin: {
      welcome: 'वापसी पर स्वागत है, एडमिन!',
      subtitle: 'पोर्टल में लॉगिन करें',
      label: 'मोबाइल नंबर या ईमेल',
      password: 'पासवर्ड',
      remember: 'याद रखें',
      forgot: 'पासवर्ड भूल गए?',
      login: 'लॉगिन',
      noAccount: 'खाता नहीं है?',
      signUp: 'साइन अप',
      show: 'दिखाएँ',
      hide: 'छुपाएँ',
    },
    register: {
      title: 'पंजीकरण',
      subtitle: 'कृपया अपनी जानकारी भरें',
      fullName: 'पूरा नाम',
      gender: 'लिंग',
      email: 'ईमेल',
      password: 'पासवर्ड',
      phone: 'फोन नंबर',
      dob: 'जन्म तिथि',
      age: 'उम्र',
      education: 'शैक्षणिक स्तर',
      preferredField: 'पसंदीदा क्षेत्र',
      careerGoal: 'करियर लक्ष्य',
      city: 'शहर',
      state: 'राज्य',
      pincode: 'पिनकोड',
      reset: 'रीसेट',
      submit: 'रजिस्टर करें',
      submitting: 'भेजा जा रहा है...',
      selectGender: 'लिंग चुनें',
      selectEducation: 'शिक्षा चुनें',
      genderMale: 'पुरुष',
      genderFemale: 'महिला',
      genderOther: 'अन्य',
      required: '*',
      autoCalculated: 'स्वतः गणना',
      placeholderName: 'अपना पूरा नाम दर्ज करें',
      placeholderEmail: 'example@gmail.com',
      placeholderPassword: 'मजबूत पासवर्ड डालें',
      placeholderPhone: '10 अंकों का फोन नंबर',
      placeholderField: 'उदा. आईटी, मार्केटिंग, डिज़ाइन',
      placeholderCareer: 'आप क्या बनना चाहते हैं? (उदा. सॉफ्टवेयर इंजीनियर)',
      placeholderCity: 'अपना शहर दर्ज करें',
      placeholderState: 'अपना राज्य दर्ज करें',
      placeholderPincode: '6 अंकों का पिनकोड',
      languageTitle: 'अपनी भाषा चुनें',
      close: 'बंद करें',
      english: 'English',
      hindi: 'हिन्दी',
      bengali: 'বাংলা',
    },
    modal: {
      title: 'अपनी भाषा चुनें',
      close: 'बंद करें',
    },
  },
  bn: {
    nav: {
      home: 'হোম',
      about: 'মূল্যায়ন সম্পর্কে',
      assessment: 'মূল্যায়ন',
      language: 'ভাষা',
      login: 'লগইন',
      signUp: 'সাইন আপ',
      admin: 'অ্যাডমিন',
    },
    auth: {
      welcome: 'স্বাগতম!',
      subtitle: 'আপনার ক্যারিয়ার মূল্যায়ন চালিয়ে যেতে লগইন করুন',
      label: 'মোবাইল নম্বর বা ইমেইল',
      password: 'পাসওয়ার্ড',
      remember: 'মনে রাখুন',
      forgot: 'পাসওয়ার্ড ভুলে গেছেন?',
      login: 'লগইন',
      noAccount: 'অ্যাকাউন্ট নেই?',
      signUp: 'সাইন আপ',
      show: 'দেখান',
      hide: 'লুকান',
      submit: 'লগইন',
    },
    admin: {
      welcome: 'স্বাগতম, অ্যাডমিন!',
      subtitle: 'পোর্টালে লগইন করুন',
      label: 'মোবাইল নম্বর বা ইমেইল',
      password: 'পাসওয়ার্ড',
      remember: 'মনে রাখুন',
      forgot: 'পাসওয়ার্ড ভুলে গেছেন?',
      login: 'লগইন',
      noAccount: 'অ্যাকাউন্ট নেই?',
      signUp: 'সাইন আপ',
      show: 'দেখান',
      hide: 'লুকান',
    },
    register: {
      title: 'নিবন্ধন',
      subtitle: 'আপনার তথ্য পূরণ করুন',
      fullName: 'পূর্ণ নাম',
      gender: 'লিঙ্গ',
      email: 'ইমেইল',
      password: 'পাসওয়ার্ড',
      phone: 'ফোন নম্বর',
      dob: 'জন্ম তারিখ',
      age: 'বয়স',
      education: 'শিক্ষাগত স্তর',
      preferredField: 'পছন্দের ক্ষেত্র',
      careerGoal: 'ক্যারিয়ার লক্ষ্য',
      city: 'শহর',
      state: 'রাজ্য',
      pincode: 'পিনকোড',
      reset: 'রিসেট',
      submit: 'রেজিস্টার করুন',
      submitting: 'জমা হচ্ছে...',
      selectGender: 'লিঙ্গ নির্বাচন করুন',
      selectEducation: 'শিক্ষা নির্বাচন করুন',
      genderMale: 'পুরুষ',
      genderFemale: 'মহিলা',
      genderOther: 'অন্যান্য',
      required: '*',
      autoCalculated: 'স্বয়ংক্রিয়ভাবে গণনা',
      placeholderName: 'আপনার পুরো নাম লিখুন',
      placeholderEmail: 'example@gmail.com',
      placeholderPassword: 'শক্তিশালী পাসওয়ার্ড লিখুন',
      placeholderPhone: '১০ সংখ্যার ফোন নম্বর',
      placeholderField: 'উদা. আইটি, মার্কেটিং, ডিজাইন',
      placeholderCareer: 'আপনি কী হতে চান? (উদা. সফটওয়্যার ইঞ্জিনিয়ার)',
      placeholderCity: 'আপনার শহর লিখুন',
      placeholderState: 'আপনার রাজ্য লিখুন',
      placeholderPincode: '৬ সংখ্যার পিনকোড',
      languageTitle: 'আপনার ভাষা নির্বাচন করুন',
      close: 'বন্ধ',
      english: 'English',
      hindi: 'हिन्दी',
      bengali: 'বাংলা',
    },
    modal: {
      title: 'আপনার ভাষা নির্বাচন করুন',
      close: 'বন্ধ',
    },
  },
};

export function getStoredLanguage() {
  if (typeof window === 'undefined') return 'en';

  const saved = localStorage.getItem('careerCompassLanguage');
  return supportedLanguages.some((lang) => lang.code === saved) ? saved : 'en';
}

export function translate(key, language = getStoredLanguage()) {
  const path = key.split('.');
  const target = translations[language] || translations.en;
  let value = target;

  for (const segment of path) {
    value = value?.[segment];
    if (value === undefined) return key;
  }

  return value;
}
